### ISSUE TITLE
how to use textfms module in python in windows environment

### ISSUE THREAD

**Issue by akhileshdx** [google/textfsm#81] opened 2020-04-20 23:55 UTC
**Unable to utilize textfsm**

_- Also kindly advise whether there are any other module like textfsm to parse network output ?_

**=> Actions taken so far**

Downloaded the NTC templates from github to the below folder
Applied the CMD set command NET_TEXTFSM=C:\Users\Guest\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\textfms_GIT\templates
**=> Error code on IDLE after running the code**

Unable to run export command or anything

= RESTART: C:\Users\Guest\AppData\Local\Programs\Python\Python38-32\related\working in progress files for description.py Traceback (most recent call last): File "C:\Users\Guest\AppData\Local\Programs\Python\Python38-32\ related\working in progress files for description.py", line 13, in output = net_connect.send_command('show ip int br',use_textfsm=True) File "C:\Users\Guest\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\utilities.py", line 347, in wrapper_decorator return func(self, *args, **kwargs) File "C:\Users\Guest\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\base_connection.py", line 1443, in send_command structured_output = get_structured_data( File "C:\Users\Guest\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\utilities.py", line 277, in get_structured_data template_dir = get_template_dir() File "C:\Users\Guest\AppData\Local\Programs\Python\Python38-32\lib\site-packages\netmiko\utilities.py", line 230, in get_template_dir raise ValueError(msg) ValueError: Valid ntc-templates not found, please install https://github.com/networktocode/ntc-templates and then set the NET_TEXTFSM environment variable to point to the ./ntc-templates/templates directory.

**Comment by ktbyers** [comment] 2020-05-21 18:16
Your issue here is a Netmiko issue so you should migrate your issue to there (and close it here).

On quick glance it looks like you are probably not setting the environment variable correctly on Windows.

**Comment by harro** [comment] 2021-05-27 06:52
Yes, tangible known issues and pull requests should be discussed here. If you find a root cause that requires a change to textfsm then please propose the fix, or pull request here. We can't provide cross platform compatibility without such help.

**Closed by harro** 2021-05-27 06:52 UTC
